name: Feature Request
description: Request a new feature for the repository.
title: "[Feature Request]: "
labels: ["enhancement"]
projects: ["saturdays"]
assignees:
  - ugognw
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute your ideas!
  - type: textarea
    id: short-description
    attributes:
      label: What should we add?
      description: Also tell us, why and how to implement it?
      placeholder: Describe the feature!
      value: "A cool feature!"
    validations:
      required: true
  - type: checkboxes
    id: checklist
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://www.github.com/ugognw/saturdays/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
      label: Due Diligence
      description: It's important to check if someone has already proposed this feature
      options:
        - label: I checked for duplicate feature requests
          required: true
