name: documentation
on:
    push:
    pull_request:
        branches:
            - $default-branch
    workflow_call:

defaults:
  run:
    shell: bash

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.11'
          - name: Install Hatch
            uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc
          - name: Build documentation
            run: |
              hatch run mkdocs build
          - name: Upload static webpage files as artifact
            id: deployment
            uses: actions/upload-pages-artifact@v3
            with:
                path: docs/site
