name: linting
on:
    push:
    pull_request:
        branches:
            - $default-branch

defaults:
  run:
    shell: bash

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.11'
          - name: Install Hatch
            uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc
          - name: Run quality checks with pre-commit
            run: |
              hatch run pre-commit run --all-files
